INSERT INTO "information_schema"."tables" ("table_catalog","table_schema","table_name","table_type","self_referencing_column_name","reference_generation","user_defined_type_catalog","user_defined_type_schema","user_defined_type_name","is_insertable_into","is_typed","commit_action") VALUES 
('icecream','public','data','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','untitled_table_69','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_statistic','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_type','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_foreign_server','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_authid','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_shadow','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statistic_ext_data','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_roles','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_settings','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_file_settings','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_hba_file_rules','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_config','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_cursors','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_user_mapping','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_stat_bgwriter','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_replication_origin_status','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_subscription','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_stat_progress_vacuum','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_progress_cluster','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_attribute','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_proc','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_class','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_attrdef','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_constraint','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_inherits','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_index','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_operator','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_opfamily','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_opclass','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_am','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_amop','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_amproc','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_language','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_largeobject_metadata','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_aggregate','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_stat_progress_create_index','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_user_mappings','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_largeobject','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_statistic_ext','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_rewrite','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_trigger','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_event_trigger','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_description','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_cast','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_enum','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_namespace','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_conversion','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_depend','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_database','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_db_role_setting','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_tablespace','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_pltemplate','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_auth_members','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_shdepend','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_shdescription','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_ts_config','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_ts_config_map','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_ts_dict','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_ts_parser','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_ts_template','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_extension','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_foreign_data_wrapper','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_foreign_table','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_policy','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_replication_origin','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_default_acl','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_init_privs','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_seclabel','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_shseclabel','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_collation','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_partitioned_table','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_range','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_transform','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_sequence','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_publication','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_publication_rel','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_subscription_rel','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_group','VIEW',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_user','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_policies','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_rules','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_views','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_matviews','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_sequences','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stats','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stats_ext','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_publication_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_locks','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_available_extensions','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_available_extension_versions','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_prepared_xacts','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_prepared_statements','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_seclabels','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_sys_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_timezone_abbrevs','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_timezone_names','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_user_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_all_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_xact_all_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_sys_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_xact_sys_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_user_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_xact_user_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_all_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_all_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_sys_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_user_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_all_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_sys_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_user_indexes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_all_sequences','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_sys_sequences','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_statio_user_sequences','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_activity','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_replication','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_wal_receiver','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_subscription','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_ssl','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_gssapi','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_replication_slots','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_database','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_database_conflicts','VIEW',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','pg_catalog','pg_stat_user_functions','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_xact_user_functions','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','pg_catalog','pg_stat_archiver','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','information_schema_catalog_name','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','check_constraint_routine_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','applicable_roles','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','administrable_role_authorizations','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','collation_character_set_applicability','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','attributes','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','check_constraints','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','character_sets','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','collations','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','column_domain_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','column_column_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','column_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','column_udt_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','columns','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','constraint_column_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','schemata','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','constraint_table_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','domain_constraints','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','sql_packages','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','domain_udt_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','sequences','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','domains','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','enabled_roles','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','key_column_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','parameters','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','referential_constraints','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','sql_features','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','role_column_grants','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','routine_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','role_routine_grants','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','routines','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','sql_implementation_info','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','sql_parts','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','sql_languages','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','sql_sizing','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','sql_sizing_profiles','BASE TABLE',NULL,NULL,NULL,NULL,NULL,'YES','NO',NULL),
('icecream','information_schema','table_constraints','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','table_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','role_table_grants','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','views','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','transforms','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','triggered_update_columns','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','_pg_foreign_servers','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','triggers','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','data_type_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','udt_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','role_udt_grants','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','usage_privileges','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','element_types','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','role_usage_grants','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','user_defined_types','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','_pg_foreign_table_columns','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','view_column_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','view_routine_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','view_table_usage','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_server_options','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','column_options','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','_pg_foreign_data_wrappers','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_data_wrapper_options','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_data_wrappers','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_servers','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','_pg_foreign_tables','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','foreign_table_options','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','_pg_user_mappings','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','user_mappings','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL),
('icecream','information_schema','user_mapping_options','VIEW',NULL,NULL,NULL,NULL,NULL,'NO','NO',NULL);